version: '3.9'
services:
  copy_es:
    build: ./postgres_to_es
    image: copy_es
    container_name: copy_es
    env_file:
      - postgres_to_es/.env
    networks:
      - copy_db

  movies_database:
    image: postgres:13
    container_name: movies_database
    networks:
      - copy_db
    depends_on:
      - copy_es
    env_file:
      - .env
    ports:
      - "5432:5432"

  elasticsearch:
    container_name: es_container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    networks:
      - copy_db
    depends_on:
      - movies_database
    ports:
      - "9200:9200"

networks:
  copy_db:
    driver: bridge
